/GsimPhysicsListFactory/QGSP_BERT/buildAndRegister
/GsimPrimaryGeneratorActionFactory/GsimGeneralParticleSource/buildAndRegister gps
/gps/particle KLpi0pi0
/gps/energy 1 GeV
/gps/position 0 0 -1.507 m
/gps/direction 0 0 1
/control/execute oglsini.mac
/GsimEventAction/setVisualizationMode 1
#/GsimEventAction/setAccumulationNumber -1
/GsimTrackingAction/setBriefTrackStore true

/GsimDetector/world/setParameters 5*m 5*m 60*m
/GsimDetector/world/setOuterVisibility 0
/GsimDetectorFactory/GsimDetector/buildAndRegister e14 /world

/GsimDetectorFactory/GsimE14Membrane/buildAndRegister mbn    /world/e14  0 0 0 0 0 0
/GsimDetectorFactory/GsimE14FBAR/buildAndRegister     fbar   /world/e14  0 0 275./2.*cm 0 0 0
/GsimDetectorFactory/GsimE14NCC/buildAndRegister      ncc    /world/e14  0 0 (275.*cm-315*mm-446.6/2.*mm) 0 0 0
/GsimDetectorFactory/GsimE14CBAR/buildAndRegister     cbar   /world/e14  0 0 (134.8+550./2.)*cm 0 0 0
/GsimDetectorFactory/GsimE14BCV/buildAndRegister      bcv    /world/e14  0 0 (134.8+550./2.)*cm 0 0 0
/GsimDetectorFactory/GsimE14CV/buildAndRegister       cv     /world/e14  0 0 (-5.23+614.8)*cm 0 0 0
/GsimDetectorFactory/GsimE14CsICover/buildAndRegister cover  /world/e14  0 0 614.8*cm 0 0 0
/GsimDetectorFactory/GsimE14CSI/buildAndRegister      csi    /world/e14  0 0 (609.8+180./2.)*cm 0 0 0
/GsimDetectorFactory/GsimE14OEV/buildAndRegister      oev    /world/e14  0 0 (614.8+50./2.)*cm 0 0 0
/GsimDetectorFactory/GsimE14LCV/buildAndRegister      lcv    /world/e14  0 0 (614.8+50./2.)*cm 0 0 0
/GsimDetectorFactory/GsimE14CC03/buildAndRegister     cc03   /world/e14  0 0 (614.8+50./2.)*cm 0 0 0
/GsimDetectorFactory/GsimE14CC04/buildAndRegister     cc04   /world/e14  0 0 (614.8+95.5+31.2+(7.+0.03)*3./2.)*cm 0 0 0
/GsimDetectorFactory/GsimE14CC05/buildAndRegister     cc05   /world/e14  0 0 (614.8+242.5+2.+20.+(7.006+0.029)*3/2.)*cm  0 0 0 201305
/GsimDetectorFactory/GsimE14CC06/buildAndRegister     cc06   /world/e14  0 0 (614.8+242.5+155.5+2.+19.+(7.006+0.029)*3/2.)*cm 0 0 0 201305
/GsimDetectorFactory/GsimE14BHCV/buildAndRegister     bhcv   /world/e14  0 0 (614.8+242.5+155.5+2.0+61.0)*cm 0 0 0 201305
/GsimDetectorFactory/GsimE14BHPV/buildAndRegister     bhpv   /world/e14  0 0 (31500+723+1361-(21000+507))*mm+423.3/2.*cm 0 0 0 201305
/GsimDetectorFactory/GsimE14Shield/buildAndRegister   shield /world/e14  0 0 (614.8+479.2+100/2.)*cm 0 0 0
/GsimDetectorFactory/GsimE14BHTS/buildAndRegister     bhts   /world/e14  0 0 (31500+723+1361-(21000+507))*mm+423.3*cm+16.8*cm 0 0 0 201305

/GsimDetector/world/e14/setThisAndDaughterMtimeStore true
/GsimEventAction/setSkipEmptyData true

/GsimSpectrumFactory/GsimE14SatoSpectrum/buildAndRegister
/GsimSpectrum/GsimE14SatoSpectrum/addSpectrum Special
/GsimSpectrum/GsimE14SatoSpectrum/setDetectorShiftZ 507*mm

/GsimDetector/world/setThisUserTimeMax 1000 ns

/GsimDetectorManager/update
/run/initialize
#/run/beamOn 20
