/GsimPhysicsListFactory/QGSP_BERT/buildAndRegister

/GsimPhysicsList/switchKLDecayTable 1
/particle/select kaon0L
/particle/property/dump

# 2pi0 decay (100%) : the following 
#/particle/property/decay/select 0
#/particle/property/decay/br 0
#/particle/property/decay/select 1
#/particle/property/decay/br 0
#/particle/property/decay/select 2
#/particle/property/decay/br 0
#/particle/property/decay/select 10
#/particle/property/decay/br 1

/GsimPrimaryGeneratorActionFactory/GsimGeneralParticleSource/buildAndRegister gps
/gps/particle kaon0L
/gps/energy 1 GeV

#/gps/position +4.366 -2.940 -1507 mm
#/gps/position +5.377 +0.183 -1507 mm
#/gps/position  +6.89  +1.85 -1507 mm
/gps/position  +6.20  +1.89 -1507 mm

/gps/direction 0 0 1
#/control/execute oglsini.mac
#/GsimEventAction/setVisualizationMode 1
#/GsimEventAction/setAccumulationNumber -1
/GsimTrackingAction/setBriefTrackStore true

/GsimDetector/world/setParameters 5*m 5*m 60*m
/GsimDetector/world/setOuterVisibility 0
/GsimDetectorFactory/GsimDetector/buildAndRegister e14 /world
/GsimDetectorFactory/GsimE14Membrane/buildAndRegister mbn    /world/e14  0 0 0 0 0 0 201605
/GsimDetectorFactory/GsimE14FBAR/buildAndRegister     fbar   /world/e14  0 0 275./2.*cm 0 0 0 201605
/GsimDetectorFactory/GsimE14NCC/buildAndRegister      ncc    /world/e14  0 0 (275.*cm-315*mm-446.6/2.*mm) 0 0 0 201605
/GsimDetectorFactory/GsimE14CBAR/buildAndRegister     cbar   /world/e14  0 0 (134.8+550./2.)*cm 0 0 0 201605
/GsimDetectorFactory/GsimE14IBAR/buildAndRegister     ibar   /world/e14  0 0 (134.8+550./2.+22.75)*cm 0 0 0 201605
/GsimDetectorFactory/GsimE14IBCV/buildAndRegister     ibcv   /world/e14  0 0 (134.8+550./2.+22.75)*cm 0 0 0 201605
/GsimDetectorFactory/GsimE14BCV/buildAndRegister      bcv    /world/e14  0 0 (134.8+550-103/2.+1)*cm 0 0 0 201605
/GsimDetectorFactory/GsimE14CV/buildAndRegister       cv     /world/e14  0 0 (-5.23-0.85+614.8+2)*cm 0 0 0 201605
/GsimDetectorFactory/GsimE14CsICover/buildAndRegister cover  /world/e14  0 0 (614.8+2-0.58)*cm 0 0 0 201605
/GsimDetectorFactory/GsimE14CSI/buildAndRegister      csi    /world/e14  0 0 (609.8+180./2.+2)*cm 0 0 0 201605
/GsimDetectorFactory/GsimE14OEV/buildAndRegister      oev    /world/e14  0 0 (614.8+50./2.+2)*cm 0 0 0 201605
/GsimDetectorFactory/GsimE14CsIBackPlate/buildAndRegister plate  /world/e14  0 0 (614.8+50.+6./2.+2)*cm 0 0 0 201605
/GsimDetectorFactory/GsimE14LCV/buildAndRegister      lcv    /world/e14  0 0 (614.8+50./2.+2-0.85)*cm 0 0 0 201605
/GsimDetectorFactory/GsimE14CC03/buildAndRegister     cc03   /world/e14  0 0 (614.8+50./2.+2)*cm 0 0 0 201605
/GsimDetectorFactory/GsimE14CC04/buildAndRegister     cc04   /world/e14  0 0 (614.8+95.5+31.2+(7.+0.03)*3./2.+2)*cm 0 0 0 201605
/GsimDetectorFactory/GsimE14CC05/buildAndRegister     cc05   /world/e14  0 0 (614.8+242.5+2.+20.-2+(7.006+0.029)*3/2.+2)*cm  0 0 0 201605
/GsimDetectorFactory/GsimE14BPCV/buildAndRegister     bpcv   /world/e14  0 0 (614.8+242.5+2.+20.-2+(7.006+0.029)*3+8+100/2.+2)*cm  0 0 0 201605
/GsimDetectorFactory/GsimE14CC06/buildAndRegister     cc06   /world/e14  0 0 (614.8+242.5+155.5+2.+19.+(7.006+0.029)*3/2.+2)*cm 0 0 0 201605
/GsimDetectorFactory/GsimE14NewBHCV/buildAndRegister  newbhcv /world/e14  -0.08*cm -0.13*cm (614.8+242.5+155.5+2.+19.+(7.006+0.029)*3.+1.125+(1+0.14)+2)*cm 0 0 0 201605
/GsimDetectorFactory/GsimE14Shield/buildAndRegister   shield /world/e14  0 0 (614.8+479.2+100/2.+2)*cm 0 0 0 201605
/GsimDetectorFactory/GsimE14BHPV/buildAndRegister     bhpv   /world/e14  0 0 (614.8+479.2+100.+52)*cm+535.6/2.*cm+2*cm 0 0 0 201605
/GsimDetectorFactory/GsimE14BHGC/buildAndRegister     bhgc   /world/e14  0 0 (614.8+479.2+100.+52)*cm+535.6*cm+2*cm 0 0 0 201605
/GsimDetectorFactory/GsimE14BHTS/buildAndRegister     bhts   /world/e14  0 0 (614.8+479.2+100.+52)*cm+535.6*cm+(62.6+4.28)*cm+2*cm 0 0 0 201605

/GsimDetector/world/e14/setThisAndDaughterMtimeStore true
/GsimEventAction/setSkipEmptyData true

/GsimSpectrumFactory/GsimE14SatoSpectrum/buildAndRegister
/GsimSpectrum/GsimE14SatoSpectrum/addSpectrum Special
/GsimSpectrum/GsimE14SatoSpectrum/setDetectorShiftZ 507*mm

/GsimDetector/world/setThisUserTimeMax 1000 ns
/GsimRunAction/setCycleOfEventSeedStore 1

/GsimDetectorManager/update
/run/initialize
#/run/beamOn 20


